### ISSUE TITLE
itag option not working

### ISSUE THREAD

**Issue by tony8086** [kkdai/youtube#109]
installed the latest version (2.0.2) in termux but the -i option is not working, it always downloads the best quality audio/video as if the option is not given.

**Comment by kcubeterm** [comment]
Issue can be reproduce in ubuntu also. there's no issues with youtube side because issue can't reproduce with youtube-dl.

**Comment by codesoap** [comment]
Using git-bisect, I found that the bug was introduced with c0516c28f41b71bdbcacd468c4efcf97c2cf2cca.

**Comment by Julian-Chu** [comment]
hi guys,  sorry I am busy in this month, I will check this issue soon. Thanks for your feedback.
