### ISSUE TITLE
Should we add youtube client headers to request ?

### ISSUE THREAD

**Issue by greentornado** [kkdai/youtube#112]
Refer to this: `https://github.com/Hexer10/youtube_explode_dart/blob/master/lib/src/reverse_engineering/youtube_http_client.dart`

![Screen Shot 2020-09-22 at 2 09 05 PM](https://user-images.githubusercontent.com/280004/93852972-32e40e00-fcdd-11ea-9fab-4b956a402ced.png)

**Comment by corny** [comment]
Is there any benefit in adding these headers?

**Comment by greentornado** [comment]
to avoid getting 429 error, i guessed

**Comment by corny** [comment]
I would like to see measurements to proof this.

**Comment by greentornado** [comment]
It's hard to give measurements but I see projects like `youtube_explode_dart` and `invidious` use this in its client's header

**Comment by Julian-Chu** [comment]
hello @greentornado, 
I find the header in youtube-dl and YoutubeExplode  as well. It seems the headers are used for playlist or  batch downloading videos from one user, which is not implemented yet, so the headers should be added by new feature.

if you have the issue with http status  429, please feel to reopen this issue, we could try this solution.

ref: [YoutubeExplode](https://github.com/Tyrrrz/YoutubeExplode/blob/f800021e2be16b6aeed1bb3bbda1d3d79a331fe7/YoutubeExplode/ReverseEngineering/Responses/PlaylistResponse.cs#L149), [youtube-dl](https://github.com/ytdl-org/youtube-dl/blob/1a95953867412bc7a785f21f6bff5145b2b13fd0/youtube_dl/extractor/youtube.py#L3017)
