### ISSUE TITLE
hope http/https proxy can be supported!!

### ISSUE THREAD

**Issue by what951006** [kkdai/youtube#113]
As title

**Comment by corny** [comment]
Do you want to use `youtube` as a library or via CLI?

**Comment by what951006** [comment]
> Do you want to use `youtube` as a library or via CLI?

Nope, I just want it supported like below
```
export https_proxy=127.0.0.1:6142
```

**Comment by corny** [comment]
That change was quite easy. Check out the latest release.
You can use `HTTP_PROXY`, `http_proxy`, `HTTPS_PROXY` and `https_proxy`.
