### ISSUE TITLE
Any planning to add more sites like youtube-dl do.

### ISSUE THREAD

**Issue by kcubeterm** [kkdai/youtube#114]
Just asking . It would be really amazing if it supports few more sites like Facebook, twitter insta etc.

**Comment by dertuxmalwieder** [comment]
Seconded. A potential list is here:
https://github.com/soimort/you-get/tree/develop/src/you_get/extractors

**Comment by Julian-Chu** [comment]
@dertuxmalwieder  thanks for information.
@kcubeterm  IMHO, community will keep driving the repo, if any strong requirement, maybe we will do it, but too many sites could make disadvantages like slow bug-fix,  maintenance complexity.   suggestions are welcome.  ps: I will close this issue later if no new comment in 7 days.

**Comment by kcubeterm** [comment]
>  I will close this issue later if no new comment in 7 days.

Five days no comments. Closing this issue. I will add and maintain few sites support soon.

**Comment by corny** [comment]
@kcubeterm I'm looking forward to your contribution!
