### ISSUE TITLE
Missing step in howto use

### ISSUE THREAD

**Issue by DusteDdk** [kkdai/youtube#119]
I'm not a go person, so I don't know what I'm doing wrong, maybe I'm missing something obvious?

```
dusted@detail:~/code/go$ git clone https://github.com/kkdai/youtube.git
Cloning into 'youtube'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 873 (delta 19), reused 34 (delta 10), pack-reused 813
Receiving objects: 100% (873/873), 207.62 KiB | 940.00 KiB/s, done.
Resolving deltas: 100% (464/464), done.
dusted@detail:~/code/go$ cd youtube/
dusted@detail:~/code/go/youtube$ go run ./cmd/youtubedr
go run: no go files listed
dusted@detail:~/code/go/youtube$ 
```

Also the other instruction does little for me:
```
dusted@detail:~/code/go/youtube$ go get github.com/kkdai/youtube/v2
package github.com/kkdai/youtube/v2: cannot find package "github.com/kkdai/youtube/v2" in any of:
        /usr/lib/go-1.10/src/github.com/kkdai/youtube/v2 (from $GOROOT)
        /home/dusted/code/go/_golang/src/github.com/kkdai/youtube/v2 (from $GOPATH)
```

Can you give me a hint as to what I'm doing wrong, or update the readme if something more is needed?
Thanks in advance, and best regards :+1:

**Comment by humaidq** [comment]
What version of Go are you using? You can check with `go version`.
The `go.mod` file for this project specifies a minimum of Go 1.15.

**Comment by DusteDdk** [comment]
> What version of Go are you using? You can check with `go version`.
> The `go.mod` file for this project specifies a minimum of Go 1.15.

That did the trick, I was not aware that the go in my distribution would not work, thanks :+1:
