### ISSUE TITLE
Arch Linux build

### ISSUE THREAD

**Issue by cjsthompson** [kkdai/youtube#120]
Couldn't find it there, so I did it. 

https://aur.archlinux.org/packages/youtubedr/

**Comment by corny** [comment]
Please check out the latest release.

**Comment by cjsthompson** [comment]
I did. It's updated.

**Comment by corny** [comment]
Thanks a lot for maintaining the package for arch linux!

**Comment by cjsthompson** [comment]
Thank you for making a good youtube downloading tool that only requires glibc.

**Comment by corny** [comment]
Well, to get rid of dependency issues I added `CGO_ENABLED=0` to the compile flags. That means everything is statically linked and we don't event depend on the glibc.
