### ISSUE TITLE
argument are not taken into account when written after the video url composant

### ISSUE THREAD

**Issue by mehdi-S** [kkdai/youtube#125]
go run ./cmd/youtubedr -q hd720 RmmDMNcmIWY **_works_**
go run ./cmd/youtubedr RmmDMNcmIWY-q hd720 **_don't_**

**Comment by kkc** [comment]
I think this PR https://github.com/kkdai/youtube/pull/127 might solve your problem. 
let's wait for cobra integration.

**Comment by corny** [comment]
solved by #127
