### ISSUE TITLE
Incorrect argument index in example

### ISSUE THREAD

**Issue by marcelluseasley** [kkdai/youtube#13]
The Usage section in the readme has `currentFile, _ := filepath.Abs(os.Args[0])`, which points to the main executable. 

I think it should be `currentFile, _ := filepath.Abs(os.Args[1])`. If I am misunderstanding, then disregard.

**Comment by kkdai** [comment]
Thank you for your issue, do you consider to send your PR for this?

**Comment by kkdai** [comment]
The reason why I use `os.Args[0]` is I want to download the video file to the abs path in main executable.
Let me know if you have any question.

**Comment by kkdai** [comment]
I have changed it to home user to avoid misleading and permission. Please check this PR.   9f3e169
