### ISSUE TITLE
How to identify bitrate of audio?

### ISSUE THREAD

**Issue by prajaraksh** [kkdai/youtube#132]
When a Format contains both audio and video, how to get bit-rate of embedded audio in video.

Purpose: I want to choose best formats.

Is it possible to have something like this: https://github.com/rylio/ytdl/blob/23234633f4592edc2c1d99f48cbd8b2be7766f5a/itag.go#L61-L91

Thank you.

**Comment by corny** [comment]
Does #130 solve this issue? I just released a new version.

**Comment by prajaraksh** [comment]
I don't think so, please correct me if I was wrong.

This one looks like an up-to-date list: https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f

Consider a Itag:18, for this video: https://www.youtube.com/watch?v=wHvgUD5uKPk

Information I get is:

|AudioQuality|AverageBitrate|Bitrate|QualityLabel|
|:-|:-|:-|:-|
|AUDIO_QUALITY_LOW|183474|183502|360p|

Even though `AverageBitrate` and `Bitrate` is given, I can't find `bitrate` of either the video or audio, because they seem to be combined into one.

Thank you.

**Comment by corny** [comment]
Alright. We need to hard code the Youtube Format IDs in our source code.

**Comment by prajaraksh** [comment]
If it helps: https://gist.github.com/prajaraksh/507c8b549322f83f195b4e981b576e46

**Comment by corny** [comment]
I've added the audio quality information that we receive to the info output.

**Comment by prajaraksh** [comment]
Sorry for the delay,

Regarding the change:

1. I was trying to get information from the api, not in `info` option.
2. And I was trying to get `bit-rate` of audio file, not to which categorized section it belongs to.

I have included `itag` information to my personal project, personally no need of it.

But why didn't you add `itag` information, any specific reason?

I'm just interested to know.

Thanks a lot.

**Comment by Julian-Chu** [comment]
@prajaraksh ,  I can try to answer the question. There's no special reason for that. very straightforward, we didn't need it before, just get info from stream is enough.  So if you think it's necessary , welcome to open an issue or make PR for that!   
ps: I will close this issue when no further discussion in one week.

**Comment by nilsocket** [comment]
Hey, I'm @prajaraksh , I lost access to this account. I will see If I can make a PR.

Thank you.

**Comment by Julian-Chu** [comment]
@nilsocket 
I close this ticket. 
Looking forward to your PR . 👍
