### ISSUE TITLE
url_encoded_fmt_stream_map is null and ...

### ISSUE THREAD

**Issue by ZHANITEST** [kkdai/youtube#14]
Hello 😄 

Sadly, some videos didn't have `url_encoded_fmt_stream_map` or got `403 code`, so didn't work.

**ex.1) 3bNITQR4Uso**
```
<... skip ...>
url_encoded_fmt_stream_map => 
fflags => bulleit_block_player_pause_until_ad_start%3Dtrue% ...
<... skip ...>
```
(i made a small tool for test it with D and just split it like :`("=", "\n")`. nvm...)

**ex.2) -k5iFLYXmWU**
```
2018/12/11 00:46:06 reading answer: non 200[code=403] status code received: '<nil>'
```
(with youtubedr.exe)

**Comment by kkdai** [comment]
Thank you, I will look into this.

**Comment by kkdai** [comment]
>> http://youtube.com/get_video_info?video_id=3bNITQR4Uso

This video could not be downloaded. So it will fail. Fixed crash issue.

**Comment by kkdai** [comment]
ex 2) -k5iFLYXmWU

Don't have permission for each video link, maybe the user disables download.

**Comment by kkdai** [comment]
Mark it as fixed, let me know if you need any help.
