### ISSUE TITLE
anyone getting files OK?

### ISSUE THREAD

**Issue by cw1nte** [kkdai/youtube#143]
I think I have latest build yet I get errors trying any id on YT, it was fine until sometime mid Dec 2020 then just stopped working.

error parsing signature tokensfail logged in ttyhist, status 1

**Comment by cw1nte** [comment]
Sorry that last bit "fail logged in ttyhist, status 1" is my command history system 
the actual error output is just

error parsing signature tokens

**Comment by Julian-Chu** [comment]
hi @cw1nte 
I have run the integration tests, all tests are green. Could you provide some information like video id and your  build version?

**Comment by cw1nte** [comment]
Hi Julian, how do I get a build version for you?
If I run ./youtubedr -v 
then I just get empty fields and the go version...
I tried /youtubedr MQxdk7QOM28

**Comment by cw1nte** [comment]
Hi Julian, how do I get a build version for you?
If I run ./youtubedr -v
then I just get empty fields and the go version...
I tried ./youtubedr MQxdk7QOM28

**Comment by Julian-Chu** [comment]
hell cw1nte,
great ! You just find the issue for version command. I will open issue for it.

Do you try  " ./youtubedr download MQxdk7QOM28"?  After  a certain version, the commands are changed.

without download command
![image](https://user-images.githubusercontent.com/7224544/105420268-580f6b80-5c40-11eb-86d5-e31c60d82d6a.png)

with download command
![image](https://user-images.githubusercontent.com/7224544/105420317-6cebff00-5c40-11eb-9bd7-6760eb242f9a.png)

I suppose you are using old version, maybe download the newest version again can solve the issue.  If any problem, please let us know.

**Comment by cw1nte** [comment]
Hi,
I have tried to update latest and build here with go, there may be an ssh certificate problem stopping me get updates... Not had time to dig into that one yet.
Last tried 13 Jan:
$ go get -u github.com/kkdai/cmd/youtube
# cd .; git clone -- https://github.com/kkdai/cmd /Users/colinwin/go/src/github.com/kkdai/cmd
Cloning into '/Users/colinwin/go/src/github.com/kkdai/cmd'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/kkdai/cmd/youtube: exit status 128

I have looked briefly into work arounds for the username issue without result.
But the old version WAS working OK in early December, last. Looking at the github files I could not really find any code changes since then that might explain - and that was what I was really interested in for my own project!

I for sure have the version without download command.
$ ./youtubedr download MQxdk7QOM28
extractVideoID failed: the video id must be at least 10 characters long

$ ./youtubedr version
extractVideoID failed: the video id must be at least 10 characters long

./youtubedr -version
Version:
Commit:
Date:
Go Version:  go1.14.2

**Comment by cw1nte** [comment]
Oops, can't edit that post but this was the pasted text..

`$ go get -u github.com/kkdai/cmd/youtube
# cd .; git clone -- https://github.com/kkdai/cmd /Users/colinwin/go/src/github.com/kkdai/cmd
Cloning into '/Users/colinwin/go/src/github.com/kkdai/cmd'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/kkdai/cmd/youtube: exit status 128
fail logged in history log DB, status 1
`

**Comment by Julian-Chu** [comment]
@cw1nte  could you try "go get -u github.com/kkdai/youtube/v2/cmd/youtubedr" ?

**Comment by greentornado** [comment]
Btw, I'm getting error for this id `PbP0_yYXcHU`, could someone check ?

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12e78b9]

goroutine 1 [running]:
github.com/kkdai/youtube/v2.(*Client).GetStreamURLContext(0xc00027f280, 0x145a0c0, 0xc000016178, 0xc000452100, 0x0, 0xc0004aa000, 0x335, 0x0, 0x0)
	/Users/Hai/Golang/pkg/mod/github.com/kkdai/youtube/v2@v2.4.1/client.go:84 +0x29
github.com/kkdai/youtube/v2.(*Client).GetStreamURL(...)
	/Users/Hai/Golang/pkg/mod/github.com/kkdai/youtube/v2@v2.4.1/client.go:79
```

**Comment by john-black-3k** [comment]
@greentornado 
I tried with the latest version 2.4.1 and I am not getting this error. I tested with this command:
```
youtubedr download -q 135 PbP0_yYXcHU
```
and sometimes I am getting a `unexpected status code: 204` error and sometimes it downloads a 5 seconds video. I think it is because this is a live stream URL. Can these be downloaded?

**Comment by Julian-Chu** [comment]
got same like @john-black-3k , it seems like  live stream issue, need to check again  when the live stream is finished

**Comment by Julian-Chu** [comment]
any update?

**Comment by greentornado** [comment]
I got some signature error

```
2021/02/24 11:48:47 GET https://youtube.com/get_video_info?video_id=_EVCman5puE&eurl=https://youtube.googleapis.com/v/_EVCman5puE
{ItagNo:18 URL: MimeType:video/mp4; codecs="avc1.42001E, mp4a.40.2" Quality:medium Cipher:s=CcwZALH-6r1pWyCW7ADg_4RDRYYQK2RnP38rrGq7XcAICo2mr6FnLlSvL0SZde5AqqE26kvYVCCSDaOR2Un_8ZpXAIARw8JQ0qOAgOAg&sp=sig&url=https://r7---sn-42u-i5oee.googlevideo.com/videoplayback%3Fexpire%3D1614163728%26ei%3DsNo1YLyKCtGmlQTIj4SYBg%26ip%3D118.70.118.219%26id%3Do-ACLc5iQASegSz_a21N4VwyC8Gsihefh9RTCdkU2sG6QQ%26itag%3D18%26source%3Dyoutube%26requiressl%3Dyes%26mh%3D1h%26mm%3D31%252C26%26mn%3Dsn-42u-i5oee%252Csn-npoe7ns7%26ms%3Dau%252Conr%26mv%3Dm%26mvi%3D7%26pl%3D21%26initcwndbps%3D1682500%26vprv%3D1%26mime%3Dvideo%252Fmp4%26ns%3DIAe1EbnjcYnzwRoSu3APGjsF%26gir%3Dyes%26clen%3D24221634%26ratebypass%3Dyes%26dur%3D285.675%26lmt%3D1595074853156436%26mt%3D1614141875%26fvip%3D3%26fexp%3D23983797%26c%3DWEB%26txp%3D5432434%26n%3DWTU_HH8nVrX613TN%26sparams%3Dexpire%252Cei%252Cip%252Cid%252Citag%252Csource%252Crequiressl%252Cvprv%252Cmime%252Cns%252Cgir%252Cclen%252Cratebypass%252Cdur%252Clmt%26lsparams%3Dmh%252Cmm%252Cmn%252Cms%252Cmv%252Cmvi%252Cpl%252Cinitcwndbps%26lsig%3DAG3C_xAwRQIhAL0wXXMPraK_afsEmqzQfNJiIqujXPeFG4nxG_Jj8qokAiB-s81L85xPfzEos1x-8jYcySR6LgzYRRrSs7il8WBIjQ%253D%253D Bitrate:678477 FPS:30 Width:640 Height:360 LastModified:1595074853156436 ContentLength:24221634 QualityLabel:360p ProjectionType:RECTANGULAR AverageBitrate:678299 AudioQuality:AUDIO_QUALITY_LOW ApproxDurationMs:285675 AudioSampleRate:44100 AudioChannels:2 InitRange:<nil> IndexRange:<nil>}
2021/02/24 11:48:48 GET https://youtube.com/embed/_EVCman5puE?hl=en
2021/02/24 11:48:48 GET https://youtube.com/s/player/5a096a9f/player_ias.vflset/en_US/base.js
error parsing signature tokens (#obj=0, #func=0)
```

**Comment by greentornado** [comment]
Please check :d

**Comment by Julian-Chu** [comment]
@greentornado  , thank for info.
 I think it's the problem youtube changes its deciper signature again.  We try to fix it soon.

**Comment by cw1nte** [comment]
@Julian-Chu 25 Jan, OP here... @cw1nte could you try "go get -u github.com/kkdai/youtube/v2/cmd/youtubedr" ???
I get a fail: $ go get -u github.com/kkdai/youtube/v2/cmd/youtubedr
package github.com/kkdai/youtube/v2/cmd/youtubedr: cannot find package "github.com/kkdai/youtube/v2/cmd/youtubedr" in any of:
	/usr/local/go/src/github.com/kkdai/youtube/v2/cmd/youtubedr (from $GOROOT)
	/Users/colinwin/go/src/github.com/kkdai/youtube/v2/cmd/youtubedr (from $GOPATH)
fail logged in history log DB, status 1 [MY LOGGING NOTE]

I have run with various mixes of switches among -v(verbose) -i -x but did not get any more information ...
I do not do much in go and have been very busy elsewhere, so apologies for not getting back. I tried a number of similar commands to get some sort of new version built. In fact I have never had success with specific go package versions and have no time to find out how it is meant to be set up, it seems a complex area trying to suit multiple differing needs of sub- and main projects... 

go version go1.14.2 darwin/amd64

**Comment by Julian-Chu** [comment]
@greentornado 
I think yt fixed it,  current version youtube should works

@cw1nte  thanks for feedback, I think we should update document and guide to be more friendly. Hope it can help u when u have time to come back. I will put it into plan

**Comment by greentornado** [comment]
@Julian-Chu i see it working again, thanks
