### ISSUE TITLE
Socks5 support is needed

### ISSUE THREAD

**Issue by ywwyewenwei** [kkdai/youtube#155]
I can not get youtube without socks5.

**Comment by corny** [comment]
Please try to set the the environment variable `HTTP_PROXY` as described in https://www.reddit.com/r/golang/comments/acqhxu/fun_fact_httpdefaulttransport_natively_supports/

**Comment by ywwyewenwei** [comment]
My OS is Win10. I do it like below:
1、go to cmd 
2、make a bat file:
    set HTTP_PROXY="socks5://127.0.0.1:10080"
    youtubedr.exe download "https://www.youtube.com/watch?v=UOpgS3JDs10&t=645s"
3、Error Msg：
Get "https://youtube.com/get_video_info?video_id=UOpgS3JDs10&eurl=https://youtube.googleapis.com/v/UOpgS3JDs10": dial tcp 108.160.165.173:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by corny** [comment]
Please try the `fix-proxy` branch. You can fetch and install it via:
```sh
go install github.com/kkdai/youtube/v2/cmd/youtubedr@fix-proxy
```

**Comment by corny** [comment]
@ywwyewenwei  Does this solve your problem?
