### ISSUE TITLE
Index out of range when trying to download

### ISSUE THREAD

**Issue by nikooo777** [kkdai/youtube#17]
Hello, I am trying to download a video through your library and I'm getting the following:

```
[niko:~/Downloads] 2s $ youtubedr https://www.youtube.com/watch?v=FHpvI8oGsuQ
2019/05/27 21:28:09 [https://www.youtube.com/watch?v=FHpvI8oGsuQ]
2019/05/27 21:28:09 download to dir= /home/niko/Downloads
2019/05/27 21:28:09 Found video id: 'FHpvI8oGsuQ'
2019/05/27 21:28:09 url: http://youtube.com/get_video_info?video_id=FHpvI8oGsuQ
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/kkdai/youtube.(*Youtube).StartDownload(0xc42001c4e0, 0xc4200d2960, 0x14, 0x7949c0, 0xc42018ebf0)
        /home/niko/go/src/github.com/kkdai/youtube/youtube.go:59 +0x3b6
main.main()
        /home/niko/go/src/github.com/kkdai/youtube/youtubedr/main.go:20 +0x29a

```

Any clues?

**Comment by kkdai** [comment]
Did you get the latest version of the code?
This video cannot be downloaded.

**Comment by nikooo777** [comment]
yes I used the latest version. It will work fine if you use youtube-dl, I believe working around this issue requires understanding what is going on.

**Comment by kkdai** [comment]
I could not download video success via youtube-dl 

![image](https://user-images.githubusercontent.com/2252691/58764667-a7e97c80-859c-11e9-8643-55747e1ca44d.png)

**Comment by nikooo777** [comment]
I believe you need to install ffmpeg using `sudo apt install ffmpeg` first, then it works.
https://scrn.storni.info/2019-06-02_19-23-17-706556246.png

**Comment by kkdai** [comment]
Thank you, I will install ffmpeg and check again.

**Comment by kkdai** [comment]
Index out of range fixed in 77f6ae3451c51ff850b258818678d3ab5fc817a4
But because signature change, so currently it block by #18

**Comment by kkdai** [comment]
Fixed program error by adding more error handle of video info parsing. 
https://github.com/kkdai/youtube/commit/705abb9455022ab8e713c746a445407a6fae0f9d

Next step will add MKV video downloading.

**Comment by G-Bruin** [comment]
![image](https://user-images.githubusercontent.com/20853074/68367158-0203f480-0170-11ea-93cf-27d4cac440a6.png)
could resolve your problem

**Comment by kkdai** [comment]
Fixed by https://github.com/kkdai/youtube/pull/27
