### ISSUE TITLE
Download video get error code 403

### ISSUE THREAD

**Issue by kkdai** [kkdai/youtube#18]
The signature pattern has change.

2019/08/04 01:05:02 Download to file= /Users/evan/Movies/yotubedr/dl.mp4

2019/08/04 01:05:08 reading answer: non 200[code=403] status code received: '<nil>'
err: non 200 status code received

Refer following change in python youtube-dl to fix this block:

- https://github.com/ytdl-org/youtube-dl/issues/21469
- https://github.com/ytdl-org/youtube-dl/pull/21476

**Comment by vmatt** [comment]
Fixed by removing "&signature=..." string from the URL. 
[See the the proposed modifications here](https://github.com/kkdai/youtube/compare/master...vmatt:patch-1)

**Comment by kkdai** [comment]
Thank you @vmatt, this issue fixed by #19.
