### ISSUE TITLE
JavaScript interpreter

### ISSUE THREAD

**Issue by 89z** [kkdai/youtube#186]
I see the current implementation uses many regular expressions:

https://github.com/kkdai/youtube/blob/40b62d7116c5feb0e61da270357a6e0d0db6ba87/decipher.go#L55-L84

I did not figure a way around this, but I have a way to simplify the process at least. Instead of parsing each line of JavaScript into Go code, you can just extract the two variables, and then run them through a JavaScript interpreter [1]. Example code:

~~~go
package main
import "github.com/robertkrimen/otto"

func main() {
   vm := otto.New()
   vm.Run("function slice(s){return s.slice(6)}")
   value, err := vm.Call("slice", nil, "south north")
   if err != nil {
      panic(err)
   }
   println(value.String() == "north")
}
~~~

Here is an example with YouTube [2]. Also the cost is small, it only adds four lines to `go.sum` [3].

1. https://github.com/robertkrimen/otto
2. https://github.com/89z/youtube/blob/v1.6.0/video.go#L18
3. https://github.com/89z/youtube/blob/v1.6.0/go.sum

**Comment by 89z** [comment]
I found another one if you are interested:

~~~go
package main
import "github.com/dop251/goja"

func main() {
   vm := goja.New()
   vm.RunString("function slice(s){return s.slice(6)}")
   var slice func(string) string
   vm.ExportTo(vm.Get("slice"), &slice)
   s := slice("south north")
   println(s == "north")
}
~~~

It adds 7 lines to `go.sum`, a little more than `otto`. However its syntax is pretty cool.

https://github.com/dop251/goja

**Comment by corny** [comment]
Alright, just 7 lines sound tiny. Much much will does the binary grow?

**Comment by 89z** [comment]
> Alright, just 7 lines sound tiny. Much much will does the binary grow?

In that regard, Otto is really the better option. Here are results with `go build -ldflags -s`:

what        | size
------------|--------
hello world | 859,648
Otto        | 3,484,160
Goja        | 7,831,552

**Comment by 89z** [comment]
Closing this, as you dont need JavaScript anymore:

https://github.com/89z/mech/blob/master/youtube/android.go

**Comment by corny** [comment]
I've added https://github.com/dop251/goja to solve #219

**Comment by 89z** [comment]
Sorry, I should have updated this post. The packages I mentioned before are good options, but I think its maybe overkill for this use case. Probably better would be a lighter weight solution, as in a JavaScript parser or lexer. This is a good option:

https://godocs.io/github.com/tdewolff/parse/v2/js

but if you want to leave the code as is, I understand.

**Comment by corny** [comment]
Well, the javascript code to decrypt the `n` parameter contains `forEach` and helper functions. Goja is perfect for this case.

**Comment by 89z** [comment]
Ive been meaning to ask someone, why do you choose to only support the WEB client:

https://github.com/kkdai/youtube/blob/b655d9a3019321c5757a97abb69745f4ec1389c0/client.go#L117-L120

the ANDROID client for example, requires no `n` parameter, so no JavaScript would be needed.
