### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by Mulac** [kkdai/youtube#187]
Running `ExampleClient()` in [example_client.go](https://github.com/kkdai/youtube/blob/master/example_test.go) with any videoID.  For example take *MBMSwDESLuc*, or https://www.youtube.com/watch?v=MBMSwDESLuc.

I get the same result using the CLI: the mp4 successfully downloads but with no audio.  Has anyone else had this issue or know where I could be going wrong?

----
using go version 1.16.3 linux/amd64
Installed via `go get github.com/kkdai/youtube/v2`

**Comment by 89z** [comment]
Yeah thats normal. That example is just getting the first format:

https://github.com/kkdai/youtube/blob/40b62d7116c5feb0e61da270357a6e0d0db6ba87/example_test.go#L22

which is usually this:

~~~
itag: 137 bitrate: 2723859 height: 1080 mimetype: video/mp4; codecs="avc1.640028"
~~~

**Comment by Julian-Chu** [comment]
hi @Mulac ,  
@89z  has already explained the code in detail.  the 1080p video in youtube is split to video and audio
 You can use `-q` flag to force download  small/medium/hd1080 video with audio.
 https://github.com/kkdai/youtube#download-video-with-specific-quality
 
 If any further question, please let us know

**Comment by Mulac** [comment]
Thanks both!  Went through all the Formats and found all I needed.
