### ISSUE TITLE
Download audio only using the package

### ISSUE THREAD

**Issue by vivekmurali** [kkdai/youtube#193]
Is there a way I can download only the audio, or download high-quality video with audio using the package. 

I am able to download the hd1080 video but it has no audio, and the lower quality ones, don't seem to play even though a content length and an audio quality label are shown. 

Any help would be amazing thanks!

**Comment by thisistorsten** [comment]
Yes you need to download audio and video dash and put it together using ffmpeg.

Here is an example app who demonstrate it.

https://tspmd.de

**Comment by vivekmurali2k** [comment]
> Yes you need to download audio and video dash and put it together using ffmpeg.
> 
> Here is an example app who demonstrate it.
> 
> https://tspmd.de

Yeah but, I want to know how they do it, they've managed to do it for their cli, so trying to understand the process to use the package to do it on my own application.

**Comment by corny** [comment]
You find the command here: https://github.com/kkdai/youtube/blob/c10404a934c84722f29a8825907cf0d5f0241fcc/downloader/downloader.go#L99

**Comment by vivekmurali2k** [comment]
> You find the command here:
> 
> https://github.com/kkdai/youtube/blob/c10404a934c84722f29a8825907cf0d5f0241fcc/downloader/downloader.go#L99

Hey, I understand the ffmpeg command, however, you're giving the audio file as an input, I'm having trouble downloading that audio file in the first place. I am able to get any quality video but without sound, I just need the audio version of the video.

**Comment by corny** [comment]
You need to select a format that only contains audio:
```golang
        videoID := "BaW_jenozKc"
	client := youtube.Client{}
	info, err := client.GetVideo(videoID)

	// youtube Itag for m4a audio
	format := info.Formats.FindByItag(140)
	stream, _, err := client.GetStream(info, format)
```
