### ISSUE TITLE
[Bug][v2.7.0] ./client.go:226:9: undefined: io.ReadAll

### ISSUE THREAD

**Issue by adam0x01** [kkdai/youtube#194]
**How to reproduce:**
```bash
# my env: go version go1.15.6 darwin/amd64
git checkout v2.7.0
go run ./cmd/youtubedr info https://www.youtube.com/watch\?v\=rFejpH_tAHM
./client.go:226:9: undefined: io.ReadAll
```

![image](https://user-images.githubusercontent.com/842218/119152961-60a76f80-ba83-11eb-8e23-8d8bcb3399ab.png)

**Comment by corny** [comment]
ReadAll has been moved from `ioutil` to `io` in Go 1.16.
Please upgrade you Go version to 1.16.

**Comment by corny** [comment]
You can also use the provided binary:
https://github.com/kkdai/youtube/releases/download/v2.7.0/youtubedr_2.7.0_darwin_amd64.tar.gz

**Comment by adam0x01** [comment]
But the `go.mod` file still says `go 1.15`  https://github.com/kkdai/youtube/blob/v2.7.0/go.mod#L3
Any plan to update it and Readme?

**Comment by corny** [comment]
I've just updated the `go.mod` and the Readme.

**Comment by adam0x01** [comment]
Cool. Thanks~👍
