### ISSUE TITLE
GetVideo() got "unexpected status code: 404"

### ISSUE THREAD

**Issue by surpassly** [kkdai/youtube#196]
go version 1.16.5
github.com/kkdai/youtube/v2 v2.7.0
video https://www.youtube.com/embed/wmqJYHH-hvI

**Comment by raitonoberu** [comment]
I have the same problem. If I try several times, it works (about 1 out of 5 times).
Go 1.16.4, youtube v2.7.0, video https://www.youtube.com/watch?v=dfkdRBAik0o (actually all the videos I've tried)

**Comment by drunlade** [comment]
Looks like the video_info endpoint this relies on is being shutdown.

Possible the work being done on https://github.com/tombulled/innertube my be a way forward.

**Comment by marcio199226** [comment]
> Looks like the video_info endpoint this relies on is being shutdown.
> 
> Possible the work being done on https://github.com/tombulled/innertube my be a way forward.

That's not a good news...Do you have any info about it ?

**Comment by 89z** [comment]
I think I have a workaround for this. If you make a request like this:

~~~
curl -o mobile.html -A iPad https://m.youtube.com/watch?v=NMYIVsdGfoo
~~~

Inside the HTML, you have a node like this:

~~~html
<script nonce="rnllSB3lBoQNKekJVVmrOA">var ytInitialPlayerResponse = {"respons...
...NOWN"}}}],"timestamp":{"seconds":"1624028141","nanos":546973023}}}};</script>
~~~

That has basically all the same data as the old endpoint. I am working on a solution (in Go) as we speak. Please be patient. I have my own package for this here:

https://pkg.go.dev/github.com/89z/mech/youtube

but again, I have not pushed anything yet.

**Comment by raitonoberu** [comment]
YouTube now uses a different API located at `https://www.youtube.com/youtubei/v1/<ep>`. The guys from Pytube are also working on a solution: https://github.com/pytube/pytube/issues/1021

**Comment by 89z** [comment]
Ok, with all the talk, I am not sure about the future of `get_video_info`, but I seemed to have fixed the issue with my package:

https://github.com/89z/mech/commit/640df95604684bf74633c68fe9c676f69fa17112

For me, the solution was just adding these:

~~~go
val.Set("c", "TVHTML5")
val.Set("cver", "4.19700101")
~~~

With `cver`, the first number needs to be `4` or more, and the rest is just any date, I used Unix epoch. If anyone want to test my package (or command line tool), help yourself. I pushed a new tag.

**Comment by drunlade** [comment]
> Ok, with all the talk, I am not sure about the future of `get_video_info`, but I seemed to have fixed the issue with my package:

Are you sure? Because the concensus right now is that `get_video_info` still works **sometimes** but is on the way out. I also thought I'd fixed it with some tweaks to the URL but turned out I was just getting good responses at the time and later it stoppped working again.

**Comment by 89z** [comment]
> Are you sure? Because the concensus right now is that `get_video_info` still
> works **sometimes** but is on the way out. I also thought I'd fixed it with
> some tweaks to the URL but turned out I was just getting good responses at
> the time and later it stoppped working again.

Here is result with `github.com/89z/mech/youtube@v1.12.9`:

~~~
PS C:\> youtube -i youtube.com/watch?v=NMYIVsdGfoo
GET  https://www.youtube.com/get_video_info?c=TVHTML5&cver=4.19700101&eurl=https%3A%2F%2Fwww.youtube.com&html5=1&video_id=NMYIVsdGfoo
author: Aphex Twin - Topic
title: Goon Gumpas
countries: []

itag 137, height 1080, 501.1 kb/s, 7.0 MB, video/mp4; codecs="avc1.640020"
itag 248, height 1080, 336.6 kb/s, 4.7 MB, video/webm; codecs="vp9"
itag 136, height 720, 236.7 kb/s, 3.3 MB, video/mp4; codecs="avc1.64001f"
itag 247, height 720, 113.9 kb/s, 1.6 MB, video/webm; codecs="vp9"
itag 135, height 480, 107.7 kb/s, 1.5 MB, video/mp4; codecs="avc1.4d401e"
itag 244, height 480, 65.0 kb/s, 919.2 kB, video/webm; codecs="vp9"
itag 134, height 360, 57.1 kb/s, 810.0 kB, video/mp4; codecs="avc1.4d4015"
itag 243, height 360, 40.3 kb/s, 574.1 kB, video/webm; codecs="vp9"
itag 133, height 240, 30.0 kb/s, 435.3 kB, video/mp4; codecs="avc1.4d400c"
itag 242, height 240, 25.7 kb/s, 368.9 kB, video/webm; codecs="vp9"
itag 160, height 144, 16.3 kb/s, 225.1 kB, video/mp4; codecs="avc1.4d400b"
itag 278, height 144, 17.9 kb/s, 260.7 kB, video/webm; codecs="vp9"
itag 140, height 0, 131.2 kb/s, 2.0 MB, audio/mp4; codecs="mp4a.40.2"
itag 249, height 0, 54.8 kb/s, 788.1 kB, audio/webm; codecs="opus"
itag 250, height 0, 72.3 kb/s, 1.1 MB, audio/webm; codecs="opus"
itag 251, height 0, 139.0 kb/s, 2.0 MB, audio/webm; codecs="opus"
~~~

> EDIT: Oh hang on, I should have read you're link. You don't use the `get_video_info`. Hah.

Yeah, I do:

https://github.com/89z/mech/blob/640df956/youtube/video.go#L31

**Comment by drunlade** [comment]
> > EDIT: Oh hang on, I should have read you're link. You don't use the `get_video_info`. Hah.
> 
> Yeah, I do:
> 
> https://github.com/89z/mech/blob/640df956/youtube/video.go#L31

Huh. I followed you're link to the commit and the first thing I see in the readme is `https://www.youtube.com/youtubei/v1/<ep>` which made me think you were using that instead of `get_video_info`.

Oh well. It'll be nice if that is a fix but I suspect youtube is moving to drop that API entirely, unless there's a bunch of devices that require it and can't be updated?

**Comment by 89z** [comment]
> Huh. I followed you're link to the commit and the first thing I see in the readme is `https://www.youtube.com/youtubei/v1/<ep>` which made me think you were using that instead of `get_video_info`.

I am considering adding or replacing `get_video_info` with the other API. But as I just learned of its existence today, its not done yet.

> It'll be nice if that is a fix but I suspect youtube is moving to drop that API entirely, unless there's a bunch of devices that require it and can't be updated?

As you have literally no evidence to back up this claim, I would strongly suggest you stop pushing it. All youre doing at this point is just gossip and pushing FUD.

**Comment by drunlade** [comment]
> As you have literally no evidence to back up this claim (and from your profile, no programming experience [1]), I would strongly suggest you stop pushing it. All youre doing at this point is just gossip and spreading FUD, and actively wasting peoples time who are actually working on the problem.
> 
>     1. https://github.com/drunlade

That's a rather juvinile response, as was deleting the quoted message, as well as linking to my profile as some sort of attack on my ability to have comments and input. You won't see anything on there because it's all on company repositories, which are private. Personally I think sixteen years of experience is enough to have some input.

Having read the threads, comments and issues raised on other projects, the conclusion by many (most?) developers is that the API is being retired and replaced with the `youtubei` API. They of course could be wrong, but I trust that people making all these libs have some idea what they're talking about.

**Comment by 89z** [comment]
As an actual contributor on this project [1], and as someone with actual experience in the different YouTube APIs [2][3], I would advise anyone reading this thread to ignore @drunlade, as they have no provable experience with YouTube API, or even computer programming in general.

It seems their only goal is to spread doubt and uncertainty about the current situation.

1. https://github.com/kkdai/youtube/commits?author=89z
2. https://pkg.go.dev/github.com/89z/mech/youtube
3. https://superuser.com/a/773998

**Comment by drunlade** [comment]
I have far better things to get on with than argue with someone who turns a discussion about code or implementation into a personal attack and an "I'm the superior developer" competetion. You're a good example of toxic behaviour, you don't discuss or explain, you insult and attack. Just consider for a moment the community you're part of and how you're actions reflect on it.

**Comment by 89z** [comment]
@drunlade did you have any constructive, referenced information to bring to the table? Otherwise I think the only reasonable conclusion, is that you are here to distract from anyone actually solving the issue.

**Comment by corny** [comment]
Related issues:
- https://github.com/ytdl-org/youtube-dl/issues/29333
- https://github.com/ytdl-org/youtube-dl/issues/29086
- https://github.com/pytube/pytube/issues/1021

If I add `c=TVHTML5&cver=7.20201028` to the `get_video_info` request, I get a 200 response, but metadata like release date and duration is missing in the response.

**Comment by 89z** [comment]
@corny I tested over 800 combinations yesterday [1], so I dont think its possible anymore to get that data from `get_video_info` anymore. So it will need to be gotten from an normal `/watch` request (`m.youtube.com`) ok too, or maybe the new `youtubei` request.

1. <https://github.com/89z/mech/blob/47a0d63c/research/2021-06-18/get_video_info/youtube.go>

**Comment by 89z** [comment]
After much research, it seems the best current option for getting the media, is making a `POST` request as `ANDROID` to `/youtubei/v1/player`:

https://github.com/89z/mech/blob/master/youtube/android.go

and for just getting video information, making a `POST` request as `WEB` to `/youtubei/v1/player`:

https://github.com/89z/mech/blob/master/youtube/web.go

in both cases, you get a pure JSON response (or Protobuf if you want), and with the `ANDROID` option, the signatures are already decrypted, which means no JavaScript mess.

**Comment by raitonoberu** [comment]
I created a PR, which seems to fix the issue (#197).

**Comment by 89z** [comment]
#197 is honestly a poor fix, and not worth committing even temporarily in my opinion.

**Comment by raitonoberu** [comment]
Well, it's been four days, and you still haven't come up with a better solution.

**Comment by esrrhs** [comment]
same problem, waiting fix
