### ISSUE TITLE
Add MKV downloading support for youtube

### ISSUE THREAD

**Issue by kkdai** [kkdai/youtube#20]
Refer to #17 

`youtubedr https://www.youtube.com/watch?v=FHpvI8oGsuQ`

Video content is MKV, need to refer https://github.com/ytdl-org/youtube-dl to add MKV download feature.

**Comment by prologic** [comment]
Do you plan to implement this?

**Comment by kkdai** [comment]
"help wanted".
I need someone to help with this issue.

**Comment by prologic** [comment]
Does [this project](https://github.com/rylio/ytdl) support MKV? Can we reuse their code if it does?

**Comment by kkdai** [comment]
Hi @prologic 
Thank you for your suggestion but https://github.com/rylio/ytdl is not working for this video `youtubedr https://www.youtube.com/watch?v=FHpvI8oGsuQ`

But `https://github.com/ytdl-org/youtube-dl` works well.
It still needs time to check and port related code from Python to Go

**Comment by prologic** [comment]
I see. Yes you are right:

```sh
$ ytdl https://www.youtube.com/watch?v=FHpvI8oGsuQ
{"level":"info","time":"2020-03-30T13:32:02+10:00","message":"Fetching video info..."}
{"level":"info","time":"2020-03-30T13:32:03+10:00","message":"Downloading to Milo: Forbidden Conversation.mp4"}
{"level":"fatal","error":"unexpected EOF","time":"2020-03-30T13:32:04+10:00"}
```

I kind of need this to work for [Tube](https://github.com/prologic/tube) and I'm currently using [ytdl](https://github.com/rylio/ytdl). It would be nice to get this working in either your library or rylio's. What is the Python library doing that either your or rylio's library isn't? Can I help in some way?

**Comment by kkdai** [comment]
Maybe just need to understand how `youtube-dl` works?

 ~/Downloads  youtube-dl https://www.youtube.com/watch\?v\=FHpvI8oGsuQ
[youtube] FHpvI8oGsuQ: Downloading webpage
[youtube] FHpvI8oGsuQ: Downloading js player vflJSBrYd
[youtube] FHpvI8oGsuQ: Downloading js player vflJSBrYd
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: Milo - Forbidden Conversation-FHpvI8oGsuQ.f137.mp4
[download] 100% of 1.40GiB in 06:00
[download] Destination: Milo - Forbidden Conversation-FHpvI8oGsuQ.f251.webm
[download] 100% of 84.07MiB in 00:20
[ffmpeg] Merging formats into "Milo - Forbidden Conversation-FHpvI8oGsuQ.mkv"
Deleting original file Milo - Forbidden Conversation-FHpvI8oGsuQ.f137.mp4 (pass -k to keep)
Deleting original file Milo - Forbidden Conversation-FHpvI8oGsuQ.f251.webm (pass -k to keep)

--- 

Maybe try to use `-k` and playback this video if it works and check whole path with the related messages.

**Comment by kkdai** [comment]
Hi @prologic this issue also fixed by https://github.com/kkdai/youtube/pull/27.
Feel free to check it.

**Comment by prologic** [comment]
Oh very nice! I'll check it out and replace my usage of `github.com/rylio/ytdl` if it works nicely. This should solve https://github.com/prologic/tube/issues/12 for me :)
