### ISSUE TITLE
Get 403 on GetStream

### ISSUE THREAD

**Issue by surpassly** [kkdai/youtube#203]
For example: 
https://www.youtube.com/embed/Nu__TzWfpss
https://www.youtube.com/embed/tqfzDTuRlps
https://www.youtube.com/embed/tul6zYBp9tA
https://www.youtube.com/embed/WYCw0WHWCAg
https://www.youtube.com/embed/G8G_UCcjEmY
When I request the decipheredURL, it always returns 403.

**Comment by Camelva** [comment]
All of those links works for me. Which version you're using? latest (v2.7.2) should work just fine

**Comment by Julian-Chu** [comment]
@surpassly , could you take a look  the version like @Camelva  mentioned?
All of them work for me as well with latest v2.7.2.
I will close this issue after 7 days  if no further questions

**Comment by surpassly** [comment]
> @surpassly , could you take a look the version like @Camelva mentioned?
> All of them work for me as well with latest v2.7.2.
> I will close this issue after 7 days if no further questions

Yes, 2.7.2 works fine, I will close this issue with this comment.
