### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by imDICO** [kkdai/youtube#209]
When you obtain the url with the FindBytag (249) of the videos of many playLists diferents, this error occurs.

"panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1417fc9]
goroutine 1 [running]:
github.com/kkdai/youtube/v2.(*Client).GetStreamURLContext(0x18572c0, 0x1602c30, 0xc000018080, 0xc000138370, 0x0, 0xc000138370, 0x0, 0x0, 0x0)"

**Comment by Julian-Chu** [comment]
hi @imDICO ,

could you please provide youtube url ?  I can't reproduce with url in example test.

**Comment by Julian-Chu** [comment]
any update?
