### ISSUE TITLE
Playlist Limit

### ISSUE THREAD

**Issue by ItsClairton** [kkdai/youtube#212]
If you use `client.GetPlaylist()` with any playlist that has more than 100 items, it will only return the first 100 items. Is there any way to exceed this limit?

Sorry for English, Google Translate.

**Comment by Julian-Chu** [comment]
do you have any playlist for this?   I guess it's the limitation of one page,  maybe we can  go through  all  pages and fetch all items, need to do some study with example, but now doesn't support it.

**Comment by muthursyamburi** [comment]
Your fork just worked like a charm and it saved a hell lot of my time!!! Thanks a ton @xesnault...
