### ISSUE TITLE
Can not get url download

### ISSUE THREAD

**Issue by tuanictu97** [kkdai/youtube#223]
I can't fetch info url download video. I receive url download is empty !
Link: https://www.youtube.com/watch?v=pFSQh_5QE40
Can you help me fix ?

**Comment by corny** [comment]
`youtubedr info https://www.youtube.com/watch\?v\=pFSQh_5QE40` works for me. Please try again with the latest release.

**Comment by tuanictu97** [comment]
I install youtubedr with brew and cmd: "youtubedr download https://www.youtube.com/watch?v=pFSQh_5QE40", It's work!
I try version 2.7.6 but list format of video return url is empty !. 
My code.
package main

import (
	"github.com/kkdai/youtube/v2"
	"log"
)

func main() {
	client := youtube.Client{}
	video, err := client.GetVideo("https://www.youtube.com/watch?v=pFSQh_5QE40")
	if err != nil {
		log.Fatal(err)
	}
	formats := video
	if formats == nil {
		log.Fatal(err)
	} else {
		log.Printf("Data: %v", formats)
	}
}

**Comment by tuanictu97** [comment]
I code go lang. Can you help me get info url download video?

**Comment by corny** [comment]
Okay, you don't want to download the stream, you want the URL of the format?

**Comment by tuanictu97** [comment]
Sorry for delay. I want return info link download for client. Client request to my server and my server return list link download for client. Can you help me?

**Comment by corny** [comment]
Just use `client.GetStreamURL(video, format)` to retrieve the stream URL for a specific video and format.

**Comment by tuanictu97** [comment]
Tks @corny !
