### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by iceluo** [kkdai/youtube#224]
Connection timeout
when i input these

./youtubedr download "https://www.youtube.com/watch?v=pFSQh_5QE40"

It shows that——

Get "https://youtube.com/embed/pFSQh_5QE40?hl=en": dial tcp 204.79.197.217:443: i/o timeout

Would someone like to give me a hand

**Comment by 89z** [comment]
I would recommend that the code be updated, to avoid a redirect:

~~~
PS C:\> curl -I https://youtube.com/embed/pFSQh_5QE40?hl=en
HTTP/2 301
location: https://www.youtube.com/embed/pFSQh_5QE40?hl=en
~~~

https://github.com/kkdai/youtube/blob/b655d9a3019321c5757a97abb69745f4ec1389c0/player_parse.go#L19

**Comment by corny** [comment]
works for me
