### ISSUE TITLE
Describe how to use as go package

### ISSUE THREAD

**Issue by iMartyn** [kkdai/youtube#228]
This might sound ungrateful, and really it's not, but if I wanted an executable to download youtube videos, I'd use `youtube-dl`.  When looking for a golang library to do this, everything points here, but the only example is the cli tool which has become so big and modular it's a really bad example.

A simple example of how to use the go package to download a hard-coded url would be immensely helpful to people finding this package looking for how to include the package in their application.

**Comment by corny** [comment]
I've added an exanple for `GetStream()`. Is it sufficient for you, or would you like to have more examples?
