### ISSUE TITLE
download too slow

### ISSUE THREAD

**Issue by tomhunts** [kkdai/youtube#232]
When I use the v2 version of the code to download the video, I found that the speed is very slow  just at 60kb/s.
And when I watch youtube videos normally, 1080p can play very smoothly
The same video I use python code to download is still very fast at 2MB/s.

It means that there is no problem with my network,
Is there a corresponding solution to this problem? thanks

**Comment by andytruong** [comment]
Found this fast: https://github.com/yt-dlp/yt-dlp

**Comment by lexuantien** [comment]
- They use io.Reader to get yeutube data then use io.Copy to copy stream to file.
https://github.com/kkdai/youtube/blob/master/downloader/downloader.go#L153
- It is better if they use os.Read and os.Write
https://opensource.com/article/18/6/copying-files-go

**Comment by vmintam** [comment]
very slow. its the same with me. Only about 50kb.

**Comment by 89z** [comment]
@lexuantien I dont think you know what youre talking about. os.Read and os.Write dont exist:

https://godocs.io/os
