### ISSUE TITLE
error unable to extract n-function name

### ISSUE THREAD

**Issue by qwerty22121998** [kkdai/youtube#240]
i got error 
```
 "error": "unable to decode nSig: unable to extract n-function name"}
```
for every video.
Do you have any workaround or solution?

**Comment by 89z** [comment]
please provide example URL

**Comment by Thomascogez** [comment]
Hello, i'm actually same issue since today, yesterday everything were working fine. My guess is that something change on youtube side 🤔

**Comment by robrotheram** [comment]
Seeing the exact same issue
URL: https://www.youtube.com/watch?v=k3WkJq478To

**Comment by 89z** [comment]
As a workaround, you can use Android client instead, as the signatures are already decrypted:

https://github.com/89z/mech/blob/v1.49.4/youtube/youtubei.go#L45-L47

**Comment by corny** [comment]
All videos are working from my computer, but on Github actions they are failing as well. We need to increase logging or create artifacts during the Github Actions run for debugging.

**Comment by paij0se** [comment]
> https://www.youtube.com/watch?v=l9nh1l8ZIJQ

Why is only working with some URLs?

**Comment by 89z** [comment]
both URLs work for me

**Comment by paij0se** [comment]
Not for me

```
panic: unable to decode nSig: unable to extract n-function name
```

**Comment by 89z** [comment]
which URL is failing?

**Comment by benjamesfleming** [comment]
PR #243 fixes this in my testing

**Comment by paij0se** [comment]
> which URL is failing?

 At least for me its almost  all the YouTube URLs.

Like this one `https://www.youtube.com/watch?v=UJLOiE8hb24`

**Comment by 89z** [comment]
are you using the tool or the module?

**Comment by paij0se** [comment]
> are you using the tool or the module?

Module
