### ISSUE TITLE
Trying to get the size of a video

### ISSUE THREAD

**Issue by eyalgolan** [kkdai/youtube#246]
Hey,

I'm trying to use `youtube.Client`'s `GetStream` function to get the the stream and size of the video I want to download, like so:
```
formats := video.Formats.WithAudioChannels() // only get videos with audio
stream, size, err := client.GetStream(video, &formats[0])
```
However, the returned `size` is always 0. How can I get the video's size?

Thanks

**Comment by corny** [comment]
Thanks for reporting, I've just written a fix.
