### ISSUE TITLE
download playlist using bash 

### ISSUE THREAD

**Issue by Kareem21227gg** [kkdai/youtube#247]
sorry for opening this issue and then closing it
but thought it will be helpful to have this snip here 
 for i in  `go run ./cmd/youtubedr list https://youtube.com/playlist?list={playlits_id} | awk '{print $2}'`;do sleep 5 && echo $i &&  go run ./cmd/youtubedr download https://youtube.com/watch?v=$i ;done

**Comment by tosiek88** [comment]
```bash
youtubedr list https://www.youtube.com/watch\?list\=<PLAYLIST> -f json | jq '.Videos[] | .ID' | xargs -P8 -I {} sh -c "youtubedr download https://www.youtube.com/watch\?v\={} -q 137"
```

Another way - parallel
