### ISSUE TITLE
Throttling issues

### ISSUE THREAD

**Issue by Mourdraug** [kkdai/youtube#248]
I ran into some heavy throttling issues, my yt download speed seems to cap at ~45 KiB/s. It doesn't seem to be related to my network connection, I can watch the same 20 minute video at full quality while simultaneously it takes 2 hours to download.

**Comment by Clashkid155** [comment]
#244, #243 and ... have fixed this issue. I think this should be closed.

**Comment by corny** [comment]
should be fixed by #286
