### ISSUE TITLE
youtubedr can not work properly

### ISSUE THREAD

**Issue by fastfading** [kkdai/youtube#25]
**youtubedr https://www.youtube.com/watch?v=54e6lBE3BoQ**

2019/12/30 09:08:57 [https://www.youtube.com/watch?v=54e6lBE3BoQ]
2019/12/30 09:08:57 download to dir= /Users/huzhang2/Movies/youtubedr
2019/12/30 09:08:57 Found video id: '54e6lBE3BoQ'
2019/12/30 09:08:57 url: https://youtube.com/get_video_info?video_id=54e6lBE3BoQ
2019/12/30 09:08:58 Title: 190107 Trouble Maker - Trouble Maker | Dance cover by 莉爷 Author: FanTastiCut Library Stream found: quality 'hd720', format 'video/mp4; codecs="avc1.64001F, mp4a.40.2"'
2019/12/30 09:08:58 Title: 190107 Trouble Maker - Trouble Maker | Dance cover by 莉爷 Author: FanTastiCut Library Stream found: quality 'medium', format 'video/webm; codecs="vp8.0, vorbis"'
2019/12/30 09:08:58 Title: 190107 Trouble Maker - Trouble Maker | Dance cover by 莉爷 Author: FanTastiCut Library Stream found: quality 'medium', format 'video/mp4; codecs="avc1.42001E, mp4a.40.2"'
2019/12/30 09:08:58 Download url= https://r1---sn-i3belne6.googlevideo.com/videoplayback?expire=1577689738&ei=Kk4JXoibGOyKs8IP6JqHmAU&ip=2001%3A420%3A5899%3A1252%3A55d7%3Acadf%3Ae1ea%3Aaa87&id=o-ABFQfCJ-KXfJTZy6op7hVn8moDnyilJ8uflnbzEVtNjo&itag=22&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-i3belne6%2Csn-i3b7kn7d&ms=au%2Crdu&mv=m&mvi=0&pl=39&initcwndbps=2277500&mime=video%2Fmp4&ratebypass=yes&dur=227.091&lmt=1546958970013208&mt=1577668064&fvip=1&fexp=23842630&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgf0tmXkOumnpdF1EmxL5y_ane5tgzTzxFuOtnrKeffQICICG-UusXI6iX0pPLNSD2qrZZqxX6KnZTEtpJEjQj-nLL

2019/12/30 09:08:58 Download to file= /Users/huzhang2/Movies/youtubedr/190107 Trouble Maker - Trouble Maker | Dance cover by 莉爷.mov

2019/12/30 09:08:58 reading answer: non 200[code=403] status code received: '<nil>'
2019/12/30 09:08:58 Download url= https://r1---sn-i3belne6.googlevideo.com/videoplayback?expire=1577689738&ei=Kk4JXoibGOyKs8IP6JqHmAU&ip=2001%3A420%3A5899%3A1252%3A55d7%3Acadf%3Ae1ea%3Aaa87&id=o-ABFQfCJ-KXfJTZy6op7hVn8moDnyilJ8uflnbzEVtNjo&itag=43&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-i3belne6%2Csn-i3b7kn7d&ms=au%2Crdu&mv=m&mvi=0&pl=39&initcwndbps=2277500&mime=video%2Fwebm&gir=yes&clen=20520392&ratebypass=yes&dur=0.000&lmt=1546959331386623&mt=1577668064&fvip=1&fexp=23842630&c=WEB&txp=2201222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgf0tmXkOumnpdF1EmxL5y_ane5tgzTzxFuOtnrKeffQICICG-UusXI6iX0pPLNSD2qrZZqxX6KnZTEtpJEjQj-nLL

2019/12/30 09:08:58 Download to file= /Users/huzhang2/Movies/youtubedr/190107 Trouble Maker - Trouble Maker | Dance cover by 莉爷.mov

2019/12/30 09:08:59 reading answer: non 200[code=403] status code received: '<nil>'
2019/12/30 09:08:59 Download url= https://r1---sn-i3belne6.googlevideo.com/videoplayback?expire=1577689738&ei=Kk4JXoibGOyKs8IP6JqHmAU&ip=2001%3A420%3A5899%3A1252%3A55d7%3Acadf%3Ae1ea%3Aaa87&id=o-ABFQfCJ-KXfJTZy6op7hVn8moDnyilJ8uflnbzEVtNjo&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-i3belne6%2Csn-i3b7kn7d&ms=au%2Crdu&mv=m&mvi=0&pl=39&initcwndbps=2277500&mime=video%2Fmp4&gir=yes&clen=14547071&ratebypass=yes&dur=227.091&lmt=1546958919927019&mt=1577668064&fvip=1&fexp=23842630&c=WEB&txp=2211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgf0tmXkOumnpdF1EmxL5y_ane5tgzTzxFuOtnrKeffQICICG-UusXI6iX0pPLNSD2qrZZqxX6KnZTEtpJEjQj-nLL

2019/12/30 09:08:59 Download to file= /Users/huzhang2/Movies/youtubedr/190107 Trouble Maker - Trouble Maker | Dance cover by 莉爷.mov

2019/12/30 09:08:59 reading answer: non 200[code=403] status code received: '<nil>'
err: non 200 status code received

 **youtubedr https://www.youtube.com/watch?v=E2_1y_9zGQs**
2019/12/30 09:13:11 [https://www.youtube.com/watch?v=E2_1y_9zGQs]
2019/12/30 09:13:11 download to dir= /Users/huzhang2/Movies/youtubedr
2019/12/30 09:13:11 Found video id: 'E2_1y_9zGQs'
2019/12/30 09:13:11 url: https://youtube.com/get_video_info?video_id=E2_1y_9zGQs
err: parse video info failed, err=no stream map found in the server's answer

**Comment by kkdai** [comment]
This file could not be download, the same result on https://github.com/iawia002/annie

```
annie https://www.youtube.com/watch\?v\=54e6lBE3BoQ
```

will hang.

**Comment by kkdai** [comment]
Fixed by https://github.com/kkdai/youtube/pull/27
