### ISSUE TITLE
安装失败，怎么解决？

### ISSUE THREAD

**Issue by briteming** [kkdai/youtube#255]
hi.

C:\Users\brite>go install github.com/kkdai/youtube/v2@latest
go: downloading github.com/kkdai/youtube/v2 v2.7.15
go: downloading github.com/bitly/go-simplejson v0.5.0
go: downloading github.com/dop251/goja v0.0.0-20220516123900-4418d4575a41
go: downloading github.com/dlclark/regexp2 v1.4.1-0.20201116162257-a2a8dda75c91
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/go-sourcemap/sourcemap v2.1.3+incompatible
package github.com/kkdai/youtube/v2 is not a main package

C:\Users\brite>

**Comment by vluzrmos** [comment]
To install it as command line globally you should do:

```bash
go install github.com/kkdai/youtube/v2/cmd/youtubedr@latest
```

and then it will be available as:

```bash
youtubedr info [VIDEO ID OR VIDEO URL HERE]
```
