### ISSUE TITLE
unable to decode nSig: SyntaxError: SyntaxError: (anonymous): Line 18:1 Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by Pilladian** [kkdai/youtube#256]
I get the following error, when trying to download a video:
unable to decode nSig: SyntaxError: SyntaxError: (anonymous): Line 18:1 Unexpected token ILLEGAL (and 4 more 

I found the problem being located in decypher.go:78 where the URL parameter "n" is being evaluated. But "n" is not used in youtube urls instead it is "v".

**Comment by galqiwi** [comment]
have the same issue, +1

**Comment by Jafter** [comment]
+1

**Comment by khodand** [comment]
+1

**Comment by splace** [comment]
+1

**Comment by alberfd** [comment]
+1

**Comment by ImVexed** [comment]
Can confirm https://github.com/kkdai/youtube/pull/257 fixes this for me

**Comment by alberfd** [comment]
with the fix the download works but very slow

**Comment by nikolaigeorgie** [comment]
+1

**Comment by corny** [comment]
I would like to add an test case. Can you please give an video ID that is affected by this issue?

**Comment by ImVexed** [comment]
> I would like to add an test case. Can you please give an video ID that is affected by this issue?

EUBfw20KKxg
