### ISSUE TITLE
Loading speed is slow

### ISSUE THREAD

**Issue by khodand** [kkdai/youtube#262]
Loading speed has become much slower after this change a27c8e6028c8156d75fe5f5cfd226d1977ea8532

**Comment by alberfd** [comment]
+1

**Comment by alberfd** [comment]
Only two with this problem?

**Comment by vinicius73** [comment]
Same here

**Comment by faelp22** [comment]
Same here

**Comment by 89z** [comment]
example URL?

**Comment by vl-ms** [comment]
@89z even the README.md url is slow

**Comment by 89z** [comment]
example URL?

**Comment by vl-ms** [comment]
oh, didn't figured out that there is a separate better version... Thank you!

**Comment by alberfd** [comment]
The issue persist to me with last version, the download speed is very slow. Tested in two diferent hosts with same results.

`wget https://github.com/kkdai/youtube/releases/download/v2.7.16/youtubedr_2.7.16_linux_amd64.tar.gz`
`tar -xf youtubedr_2.7.16_linux_amd64.tar.gz`
`./youtubedr download https://www.youtube.com/watch?v=rFejpH_tAHM`
`24.21 MiB / 45.45 MiB 53 % [================================>-----------------------------] 8m8s ] 44.45 KiB/s`

**Comment by vl-ms** [comment]
guys, seems like there is a rewrite [over here](https://github.com/89z/mech). It works much better for me at least

**Comment by kingwrcy** [comment]
same here .plz fix it

**Comment by corny** [comment]
should be fixed by #286
