### ISSUE TITLE
unable to decode nSig: SyntaxError: SyntaxError: (anonymous): Line 19:123 Missing catch or finally after try (and 1 more errors)

### ISSUE THREAD

**Issue by LouisAldorio** [kkdai/youtube#263]
2 days ago everything was working fine, but now it's broken, does anytjing change again from youtube side ?

**Comment by yezige** [comment]
我也遇到了同样的问题

**Comment by yezige** [comment]
![image](https://user-images.githubusercontent.com/11436166/185784237-4624af5c-e4cb-4b4c-8877-2fd4a0777901.png)

**Comment by joaonsantos** [comment]
goja does not seem to be able to parse the javascript that is downloaded from the youtube js player.

I tried to unminify the js but the javascript itself seems seems to have a syntax error so it does not seem to be a bug with goja.

That being said, I am not an expert on javascript so I might be wrong.
Do you have any idea what might be wrong @kkdai ?

**Comment by yezige** [comment]
又好了，有老哥给发下科普文章吗？原理到底是啥

**Comment by corny** [comment]
Please check out the latest relase 2.7.16 and leave a message if this issue still exists.
