### ISSUE TITLE
Getting a Unable to decode nSig Error

### ISSUE THREAD

**Issue by anjolaoluwaakindipe** [kkdai/youtube#264]
I wasn't getting an error before and my program was running fine, but suddenly I started getting a "unable to decode nSig" error anytime I try to run my application. I then tested with the package's Github test examples and saw that I'm getting the same error. What should I do in order to fix this.

**Comment by vanleantking** [comment]
have changed from decypher.go. 
you can visit this link: https://github.com/kkdai/youtube/issues/256
I've seen code updated on master but on tag 2.7.15 still not update yet

**Comment by corny** [comment]
Please check out the latest relase 2.7.16 and leave a message if this issue still exists.
