### ISSUE TITLE
panic: unable to decode nSig: SyntaxError: SyntaxError: (anonymous): Line 7:91 Unexpected token ILLEGAL (and 4 more errors)

### ISSUE THREAD

**Issue by gaotiansong** [kkdai/youtube#266]
panic: unable to decode nSig: SyntaxError: SyntaxError: (anonymous): Line 7:91 Unexpected token ILLEGAL (and 4 more errors)

**Comment by corny** [comment]
Please provide a youtube link or Video ID.

**Comment by ShadiestGoat** [comment]
> Please provide a youtube link or Video ID.

I have the same issue with any video - even the example video BaW_jenozKc

**Comment by ShadiestGoat** [comment]
The issue as far I can see is that it fails to find the closing bracket if its in a string. Example output:

```js
// ...
",function(d,e,f,h,l,m,n,p,q,r,w){return d(f,h,l,m,n,p,q,r,w)},
2133316051,-1080768937,-967343550,"iGIE",516224205,function(){for(var d=64,e=[];++d-e.length-32;){switch(d){case 91:d=44;continue;case 123:d=65;break;case 65:d-=18;continue;case 58:d=96;continue;case 46:d=95}e.push(String.fromCharCode(d))}return e},
-1536428084,function(){for(var d=64,e=[];++d-e.length-32;)switch(d){case 58:d=96;continue;case 91:d=44;break;case 65:d=47;continue;case 46:d=153;case 123:d-=58;default:e.push(String.fromCharCode(d))}return e},
function(d,e){e=(e%d.length+d.length)%d.length;d.splice(e,1)},
-684298006,-967343550,1004888803,"}
```

Note the open of a quote, and the closing brace, even though that is not correct syntax!

**Comment by corny** [comment]
Please check out the latest relase 2.7.16 and leave a message if this issue still exists.
