### ISSUE TITLE
unable to decode nSig: ReferenceError: myFunction is not defined at <eval>:1:1(0)

### ISSUE THREAD

**Issue by yezige** [kkdai/youtube#267]
又有新的错误了，老大我们想帮忙，我研究了代码，发现在截取一个js，然后执行，但原理不是很懂，网上也没搜到，有没有相关文章阅读推荐的

**Comment by thiagowaib** [comment]
I'm having the same issue. I was using the example code for downloading a single URL. The Error message seems to originate from the `GetStream()` method

I'm new to Go, so I don't really know much of how to solve this ;-;

**Comment by yezige** [comment]
貌似是匹配 `}` 的时候，被 `"}\u2284("` 影响了
