### ISSUE TITLE
checksum mismatch on goproxy sum server

### ISSUE THREAD

**Issue by QingsiLiu** [kkdai/youtube#272]
Problem still exists when upgrading to v2.7.17 
![image](https://user-images.githubusercontent.com/44899875/202676800-67fb1e37-2fbd-40a5-95c9-05337fa4e1de.png)

@corny 
#269

**Comment by corny** [comment]
I've released another version (`v2.7.18`). Does this solve your issue?

**Comment by QingsiLiu** [comment]
> 我发布了另一个版本 ( `v2.7.18`)。这能解决您的问题吗？
awesome! The problem is perfectly solved, thank you dude
