### ISSUE TITLE
Video title name include special character need handle when not specific output file name.

### ISSUE THREAD

**Issue by kkdai** [kkdai/youtube#28]
ex: ./youtubedr https://www.youtube.com/watch\?v\=n3kPvBCYT3E

2020/04/20 18:28:15 Download to file= /Users/USER/Movies/youtubedr/`Silhouette / Eurobeat Remix.mov`

**Comment by Julian-Chu** [comment]
What kind of approach do you prefer to fix the issuse? 
- replace special character with space (or other valid characters)
- when special character is found, use id as file name
- when special character is found, print error message and exit process
- etc..

**Comment by nitrix** [comment]
I suggest the least confusing/surprising/intrusive approach: removing invalid characters unsupported by the platform's file system.

Maybe trimming the duplicate whitespace that it may cause too.

**Comment by nitrix** [comment]
I opened a PR to help c:

**Comment by kkdai** [comment]
@Julian-Chu  Would you please help to check this PR #29,  if you have time? I have invited you as a contributor to this project.
Thank you.

**Comment by Julian-Chu** [comment]
@kkdai  my pleasure. I will take care of PR #29

**Comment by Julian-Chu** [comment]
fixed by #29
