### ISSUE TITLE
download speed is slow

### ISSUE THREAD

**Issue by kenSevLeb** [kkdai/youtube#282]
The download speed is very slow, only tens of KB

**Comment by corny** [comment]
Someone needs to figure out how other libraries solved this issue.

**Comment by i1v** [comment]
Got it:

https://github.com/i1v/mech/blob/v1.1.7/youtube/format.go#L23-L28

**Comment by corny** [comment]
What's the difference? We also download videos in 10 MB chunks if we know the content length. But how does mech retrieve the content length of a video?

**Comment by i1v** [comment]
sorry, I have catered to your laziness enough. the source code is right there, I am not doing anything fancy. if you cant be bothered to read it, then good luck to you.

**Comment by QingsiLiu** [comment]
Hello dude, I have encountered the same problem, may I know how you solved it

**Comment by jnelle** [comment]
@corny https://github.com/kkdai/youtube/blob/master/client.go#L127

You should use the Android client

**Comment by RootInit** [comment]
Also have this issue. Single digit KB downloads.

**Comment by bourne06biz** [comment]
same problem download speed is very slow, only tens of KB

**Comment by anjolaoluwaakindipe** [comment]
I'm also experiencing the same problem with download speed

**Comment by Dakauann** [comment]
I'm also experiencing this issue, a 10sec video is taking more than 15 seconds to download (30mb download internet)

**Comment by corny** [comment]
should be fixed by #286
