### ISSUE TITLE
403 issue for various vidoes I tried downloading

### ISSUE THREAD

**Issue by robrotheram** [kkdai/youtube#296]
Noticed over the last few days that I was getting 403 errors when trying to use the GetStreamURL
Even the example in the Readme does not work. 

Looking around at the other YT-DL libaries I found this issue/comment that has the same issue https://github.com/TeamNewPipe/NewPipe/issues/9038 

I have implemented  their solution:  https://github.com/yt-dlp/yt-dlp/commit/81ca451480051d7ce1a31c017e005358345a9149
and it seems to work.

**Comment by rmrf** [comment]
Thank you Robert.
