### ISSUE TITLE
Issue when downloading long video

### ISSUE THREAD

**Issue by takefy-dev** [kkdai/youtube#298]
Hey when downloading long video in HQ with Composite function i get stuck at 23% when it small duration video it work instant but for long video it does not work. https://www.youtube.com/watch?v=s0uTHZFf1f4&ab_channel=ImanGadzhiUnscripted this video does not work for example.

**Comment by itrack** [comment]
it stuck at 22% for me

**Comment by takefy-dev** [comment]
> 

Hey so i figure it out and added more routines and it worked

**Comment by corny** [comment]
Please test the branch `fix-298`. Does it solve your issue?

**Comment by takefy-dev** [comment]
> Please test the branch `fix-298`. Does it solve your issue?

I tested and for long video downloading in 1080p it's does not work

**Comment by takefy-dev** [comment]
ok i will try andlet you know
