### ISSUE TITLE
how can i get mp3 streams or convert mp4 stream into mp3 stream?

### ISSUE THREAD

**Issue by youdie323323** [kkdai/youtube#310]
i only want mp3 audio data.

**Comment by RazvanBerbece** [comment]
I did have a very brief look around the actual video download logic and it seems to be very much constrained to mp4 and video data ?

I might and I hope to be wrong though ! Would love to use this to download MP3 data from videos :)

**Comment by mathenz** [comment]
> i only want mp3 audio data.

Do you want the file exclusively as MP3 or just the audio of the video (regardless of the file format)? If you want to get the audio as MP3, you can't because YouTube doesn't allow publishing MP3 audios.

https://support.google.com/youtube/troubleshooter/2888402?hl=en
