### ISSUE TITLE
Should add support of itag.

### ISSUE THREAD

**Issue by kcubeterm** [kkdai/youtube#32]
Like youtube-dl and ytdl, youtubedr should also have itag option , in which we can download different format like webm and m4a also for audio.

**Comment by Julian-Chu** [comment]
ref in ytdl:  https://github.com/rylio/ytdl/blob/master/itag.go

**Comment by kkc** [comment]
https://gist.github.com/Marco01809/34d47c65b1d28829bb17c24c04a0096f

**Comment by kkc** [comment]
when I implement this feature, I figure out there are 2 different formats (Formats, AdaptiveFormats ) including itag. I think maybe we can create another issue to address it.

**Comment by Julian-Chu** [comment]
agree, the adaptiveFormat is used for video-only or audio-only download,  also important for downloading high resolution video.  we should create new issue to discuss the detail.

**Comment by kcubeterm** [comment]
When will you release , @kkc
