### ISSUE TITLE
unexpected status code: 400

### ISSUE THREAD

**Issue by burtgit** [kkdai/youtube#320]
The error often occurs: "unexpected status code: 400"

**Comment by shoce** [comment]
i confirm. happens on my side as well.

**Comment by inox9** [comment]
I can also confirm, error popups for random videos

**Comment by burtgit** [comment]
![Uploading 1709823897988.jpg…]()

**Comment by burtgit** [comment]
![Uploading 1709823897988.jpg…]()

**Comment by ppalone** [comment]
Issue appears to be related to https://github.com/yt-dlp/yt-dlp/issues/9316

**Comment by robrotheram** [comment]
Seeing the same issue, I manually applied @ppalone fix into my own project and I do not see the 400 error.

**Comment by natxo** [comment]
yes, changing the version in client.go fixes the 400 issues.

**Comment by cgzirim** [comment]
@natxo can you elaborate, please? What version fixes it?

**Comment by natxo** [comment]
Hi @kkdai,

 
I applied the change mentioned in https://github.com/kkdai/youtube/pull/322/files manually and it fixed the issue for me as well.

I just retested, reverting the changes has my script return a 400 from youtube.

 
Thanks for your support.

 
Regards,

Natxo


-----Oorspronkelijk bericht-----
Van:Chigozirim Igweamaka ***@***.***>
Verzonden:zo 10-03-2024 15:47
Onderwerp:Re: [kkdai/youtube] unexpected status code: 400 (Issue #320)
Aan:kkdai/youtube ***@***.***>; 
CC:Natxo Asenjo ***@***.***>; Mention ***@***.***>; 
 

 
 

@natxo can you elaborate, please? What version fixes it?
