### ISSUE TITLE
Exception 0xc0000005 0x8 0x0 0x0 

### ISSUE THREAD

**Issue by barkoder** [kkdai/youtube#324]
Running 2.10.0 on Windows 7 gives these errors.

I can confirm that 2.9.0 used to work and didn't throw these errors, but that version had #320 .

Something's broken on 2.10.0 .

    $ youtubedr version
    Exception 0xc0000005 0x8 0x0 0x0
    PC=0x0
    
    runtime.asmstdcall()
            runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x46c7b5
    rax     0x0
    rbx     0x12e41c0
    rcx     0x1339420
    rdi     0x7fffffde000
    rsi     0x22fea0
    rbp     0x22fde0
    rsp     0x22fc78
    r8      0x0
    r9      0x22fee0
    r10     0x130ad58
    r11     0x21
    r12     0x22fec0
    r13     0x1
    r14     0x12e3b60
    r15     0x0
    rip     0x0
    rflags  0x10293
    cs      0x33
    fs      0x53
    gs      0x2b

I'm looking for a non-*"just-use-Windows-8/10/11"* solution to this problem.

Thanks for any and all help.

**Comment by corny** [comment]
Since Go 1.21 the [Minimum Requirements](https://zchee.github.io/golang-wiki/MinimumRequirements/#windows) are Windows 10 and later. The support for Go 1.20 has [ended](https://endoflife.date/go).

Even if this download tool can be built with Go 1.20 today, every dependency could introduce changes that are incompatible with outdated versions of Go.

**Comment by shoce** [comment]
> I'm looking for a non-_"just-use-Windows-8/10/11"_ solution to this problem.

qemu with linux+youtubedr

**Comment by barkoder** [comment]
After configuring youtubedr.exe 2.10.1 with [VxKex](https://github.com/vxiiduu/VxKex) , I'm able to get it running on Windows 7 x64.

VxKex is amazing. It also works on other Win8+ compatible software.

Leaving a comment here in case somebody else needs to run youtubedr on Win7. Hope this helps.
