### ISSUE TITLE
add quality option

### ISSUE THREAD

**Issue by sifaaa** [kkdai/youtube#33]
1080p

**Comment by Julian-Chu** [comment]
ref https://github.com/e-alfred/ocdownloader/issues/51#issuecomment-342180714

**Comment by Julian-Chu** [comment]
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/postprocessor/ffmpeg.py
https://github.com/ytdl-org/youtube-dl#format-selection

It looks like when resolution over 720p, we will need to download video and audio seperately, after that use avconv or ffmpeg to merge into single file.

so #32  is the prerequisite for this issue

**Comment by tarun-choudhary** [comment]
That's same youtube-dl does

**Comment by Julian-Chu** [comment]
update:  now we can download adaptive stream by itag
next tasks:
- business logic to choose corresponding  video and audio to merge(plan to use best quality of both)
- check installation of ffmpeg,  execute ffmpeg to merge video and audio

**Comment by Julian-Chu** [comment]
As @kkc  in #68 mentioned,  the document is still missing.
