### ISSUE TITLE
Travis CI no longer shows as check on github pull request page

### ISSUE THREAD

**Issue by kkc** [kkdai/youtube#34]
## description

![image](https://user-images.githubusercontent.com/129365/81575148-469b7180-93d9-11ea-8b9b-e7f767da4e5f.png)

not sure why TravisCI no longer shows the result on Github page.

**Comment by Julian-Chu** [comment]
@kkdai  could you check  GitHub Apps Integration in Travis is activated?
[link](https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/#stq=&stp=0)

**Comment by kkdai** [comment]
I already enabled it for all my repo.

**Comment by Julian-Chu** [comment]
more information:  this issue happened after Aug 5, 2019.
![image](https://user-images.githubusercontent.com/7224544/81646249-33b18d00-942b-11ea-8e88-9222fbc389da.png)

**Comment by Julian-Chu** [comment]
one solution I found, hope it works.
[fails-to-report-build-status-to-github](https://travis-ci.community/t/fails-to-report-build-status-to-github/7714)

**Comment by kkdai** [comment]
![image](https://user-images.githubusercontent.com/2252691/81846054-1512d980-9584-11ea-8cf0-49ad5e5086f6.png)


I have migrated this repo fro travis-ci.org to travis-ci.com, not sure if this is root cause.

**Comment by Julian-Chu** [comment]
It seems not working yet...
maybe check this permission(in settings->Applications)  again after migration
![image](https://user-images.githubusercontent.com/7224544/81871154-88fab500-9577-11ea-9657-fda2c96874f4.png)

**Comment by Julian-Chu** [comment]
put references together:  all of them are solved by reauthorizing

[Travis UI does not link a build to correct commit on GitHub PR](https://travis-ci.community/t/travis-ui-does-not-link-a-build-to-correct-commit-on-github-pr/7711/5)

[Status of builds not being sent to GitHub for commits and pull requests](https://github.com/travis-ci/travis-ci/issues/9440#issuecomment-378637277)

[travis-ci reports are broken](https://github.com/plastex/plastex/issues/134#issuecomment-571736072)

[Pushes won’t trigger new builds anymore after the project has been inactive for a long time](https://travis-ci.community/t/pushes-wont-trigger-new-builds-anymore-after-the-project-has-been-inactive-for-a-long-time/5716/3)

**Comment by kkdai** [comment]
Permission works well.

![image](https://user-images.githubusercontent.com/2252691/82005879-1f72c780-9699-11ea-89eb-18cceb2f73e1.png)


Not sure if related this
![image](https://user-images.githubusercontent.com/2252691/82005866-15e95f80-9699-11ea-8e87-75e944ad9a72.png)

**Comment by kkdai** [comment]
Send email to support@travis-ci.com, wait for response.

**Comment by Julian-Chu** [comment]
now it works!
![image](https://user-images.githubusercontent.com/7224544/82070506-1f90b880-96d5-11ea-9fc9-ea4b84bb147a.png)

**Comment by kkdai** [comment]
果然是 Travis CI 關閉我權限  orz


![image](https://user-images.githubusercontent.com/2252691/82127356-6d94e180-97e5-11ea-80cf-ddeadfd07446.png)

**Comment by Julian-Chu** [comment]
是做什麼事了XD
@kkc 在麻煩你close了

**Comment by kkc** [comment]
okay, sure. I will close this issue. many thanks !!!
