### ISSUE TITLE
Provide the command option to get video information directly

### ISSUE THREAD

**Issue by kkc** [kkdai/youtube#47]
currently, we can get the video info when we download video. But I think it would be convenient that users can check video information before downloading it. Like we can understand what type of itag value or quality is valid.

**Comment by Julian-Chu** [comment]
add option "-itags" to available itags
example: go run main.go -itags https://www.youtube.com/watch?v=FHpvI8oGsuQ
![image](https://user-images.githubusercontent.com/7224544/84385096-49170400-abef-11ea-8b09-9ace2f099632.png)

**Comment by Julian-Chu** [comment]
closed by #51
