### ISSUE TITLE
integrated with Github Actions

### ISSUE THREAD

**Issue by Julian-Chu** [kkdai/youtube#52]
Required :
- when push and pull request
- golangci-lint (ref: https://github.com/marketplace/actions/run-golangci-lint)
- executing tests (make test-integration)

**Comment by jjmengze** [comment]
@Julian-Chu  I can pick up this issue

**Comment by Julian-Chu** [comment]
Thanks @jjmengze !

**Comment by Julian-Chu** [comment]
closed by #76
