### ISSUE TITLE
confirm every .go code style with github action  

### ISSUE THREAD

**Issue by jjmengze** [kkdai/youtube#58]
We should make sure that every pr ‘s .go file has been formatted by go fmt.

That's stupid, so let's use github action to handle this matter.

**Comment by jjmengze** [comment]
I can handle this matter

**Comment by kkdai** [comment]
Thank you @jjmengze

**Comment by kkc** [comment]
thanks a lot :)

**Comment by Julian-Chu** [comment]
closed by #76
