### ISSUE TITLE
Change on player_response json

### ISSUE THREAD

**Issue by kasuma0** [kkdai/youtube#64]
the program is failing in youtube.go at line 248, because the struct for player_response is wrong(maybe youtube has changed the response). the struct has a field called Cipher but in youtube response is called signatureCipher and has no URL field

**Comment by Julian-Chu** [comment]
@kasuma0  thanks for opening issue.  I would like to know more information, which codebase do you use,  master-branch or release version?

Julian

**Comment by kasuma0** [comment]
Hi Julian it should be v1.2.1, because i imported into my golang project and did a go mod tidy

**Comment by kasuma0** [comment]
this is the json response that came from youtube

[player_reponse.zip](https://github.com/kkdai/youtube/files/4848795/player_reponse.zip)

**Comment by Julian-Chu** [comment]
hello @kasuma0,  

Thanks for quick reply.
I found release v1.2.1 didn't include fix to cipher issue.  New release v1.2.2 is created. Please try release v1.2.2.

**Comment by Julian-Chu** [comment]
hi @kasuma0 ,
if any question, please feel free to reopen this issue
