### ISSUE TITLE
the app is re-calling youtube page for each format cipher if stream url empty

### ISSUE THREAD

**Issue by greentornado** [kkdai/youtube#67]
==> should be call only 1 time and reusing html data if possible ?

**Comment by greentornado** [comment]
<img width="792" alt="Screen Shot 2020-07-07 at 11 59 41 AM" src="https://user-images.githubusercontent.com/280004/86714428-5b972880-c049-11ea-8cd6-bce850702a02.png">

its happen when streamURL == ""

**Comment by kkc** [comment]
can you elaborate? I think every format's cipher can be different

**Comment by Julian-Chu** [comment]
hi @greentornado 
thanks for your suggestion. I didn't find this issue. Before only support muxstream
What we can do is to postpone decipher  until we got targeted stream or one step before download.

if no one pick up this ticket, I can handle it on the weekend.

**Comment by kkc** [comment]
I am not 100% sure what's the issue. I think you can pick up this ticket  :)

**Comment by greentornado** [comment]
the y.decipher function will call youtube page each time again to get the js function if there is no streamURL available. 
I mean that :D
