### ISSUE TITLE
yt livestream support?

### ISSUE THREAD

**Issue by DeadNumbers** [kkdai/youtube#72]

**Comment by Julian-Chu** [comment]
Hi @DeadNumbers ,  thanks for question.
I read the livestream API doc,  it looks like yt livestream api only supports to organize live stream events, and  API key is necessary, so we don't have plan to support it at this moment.  Any suggestion is welcome.

**Comment by DeadNumbers** [comment]
@Julian-Chu API keys not needed. First need create GET request to `https://www.youtube.com/get_video_info?video_id=%s&el=detailpage`, second find in response hlr manifest url `(?:\\"hlsManifestUrl\\":\\")(.*?)(?:\\")`, then parse `.m3u8` playlist and download stream data, decode to mp4, etc.

**Comment by Julian-Chu** [comment]
@DeadNumbers ,

Thank you for the important information.  We will do some study for that, but I guess we will put this feature in todos.

**Comment by Julian-Chu** [comment]
find reference in stackoverflow: 
https://stackoverflow.com/questions/35608686/how-can-i-get-the-actual-video-url-of-a-youtube-live-stream

**Comment by DeadNumbers** [comment]
For extract `index.m3u8` this works for me 
```Go
	r := regexp.MustCompile(`(?:\\"hlsManifestUrl\\":\\")(.*?)(?:\\")`)
	resp := httpc(fmt.Sprintf("https://www.youtube.com/get_video_info?video_id=%s&el=detailpage", video_id))
	if resp == nil {
		return "", errors.New("[get_video_info] fail")
	}
	parsed, err := url.ParseQuery(string(resp))
	if err != nil {
		return "", err
	}
	js, err := json.Marshal(parsed)
	if err != nil {
		return "", errors.New("Cant marshal query:" + err.Error())
	}
	f := r.FindString(string(js))
	if f == "" {
		return "", errors.New("Cant find playlist in detailpage")
	}
	f = strings.ReplaceAll(f, "\\", "")
	ff := strings.Split(f, "\":\"")
	if len(ff) != 2 {
		return "", errors.New("Cant find manifest")
	}
	f = strings.ReplaceAll(ff[1], "\"", "")
	return f, nil
```
