### ISSUE TITLE
cache ffmpeg in Github action

### ISSUE THREAD

**Issue by Julian-Chu** [kkdai/youtube#79]
running CI  needs ffmpeg, we could cache ffmpeg in github action to speed up workflow

ref: https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows

**Comment by kkc** [comment]
FYI
https://stackoverflow.com/questions/59269850/caching-apt-packages-in-github-actions-workflow

**Comment by Julian-Chu** [comment]
It looks like we have to handle dependency when caching apt package.
use docker image or build standalone ffmpeg can be possible solutions.
Need more study.

**Comment by Julian-Chu** [comment]
no idea what happened, now github actions install ffmpeg much faster ( ~30s, before it took longer than 2 mins)
this issue can be closed.
