### ISSUE TITLE
option to pass custom http transport please ?

### ISSUE THREAD

**Issue by greentornado** [kkdai/youtube#80]
In some machine, i need to disable ssl verification in http client, could you make it an option please.

**Comment by kkc** [comment]
I can implement this one

**Comment by Julian-Chu** [comment]
@greentornado 
Could you please check whether the option to disable SSL is enough for your requirement or you still need to pass entire transport configuration.

**Comment by greentornado** [comment]
@kkc @Julian-Chu its cool enough bro
