### ISSUE TITLE
v1.2.3  is released (important: fix decipher for unavailable download)

### ISSUE THREAD

**Issue by Julian-Chu** [kkdai/youtube#83]
* support 1080p: -q hd1080 #66 
* add progress bar #69 
* list all available streams of video with -info (-itags removed) #74 
* fix decipher function change from youtube #81 
* support skip SSL #82

**Comment by kkc** [comment]
Thanks a lot !!!

**Comment by greentornado** [comment]
Thanks for your efforts !
