### ISSUE TITLE
Add homebrew support

### ISSUE THREAD

**Issue by kkc** [kkdai/youtube#84]
This might be easier for some users to use this tool

**Comment by kcubeterm** [comment]
> This might be easier for some users to use this tool

Yea, that's cool.
 you know I have added it already in termux official repo, you can Install it by `pkg install youtubedr`

**Comment by kkc** [comment]
@kcubeterm thx for contributing it to termux official repo. it's awesome!

**Comment by kkc** [comment]
https://github.com/Homebrew/homebrew-core/pull/65343
