### ISSUE TITLE
please add codecs, birate, range, init to StreamList data

### ISSUE THREAD

**Issue by greentornado** [kkdai/youtube#86]
```
type Stream struct {
	ItagNo   int    `json:"itag"`
	URL      string `json:"url"`
	MimeType string `json:"mimeType"`
	Quality  string `json:"quality"`
	Cipher   string `json:"signatureCipher"`
}
```

Please add `codecs`, `bitrate`, `range`, `init` of `AdaptiveFormats` to the `Stream` struct please ...

**Comment by Julian-Chu** [comment]
Hi @greentornado ,

do you have to operate AdaptiveFormat directly or just need information of above properties?

**Comment by greentornado** [comment]
its perfect if i can touch AdaptiveFormat directly bro

**Comment by kkc** [comment]
sounds like we may need to expose an API?

**Comment by greentornado** [comment]
yeah because  I wanna build a dash file to play with EXO player...

**Comment by corny** [comment]
Can we merge formats and adaptive formats in a single list?

**Comment by corny** [comment]
Please check out the latest release.

**Comment by a8nJ** [comment]
https://github.com/kkdai/youtube/pull/97
