### ISSUE TITLE
Where is the binary?  Newbie issue

### ISSUE THREAD

**Issue by frrobert2** [kkdai/youtube#87]
Complete newbie question!!!

After the installation where is the youtubedr binary located?

I am running Ubuntu 20.04.

I installed go today along with youtubedr.  I tried both install methods and no errors but I cannot find youtubedr.  I search my home directory and cannot seem to find it.  I thought it would be in ~/go/bin/ but no luck.  I can see the source in ~/go/src/github/kkdai/youtube

I am not sure what I did wrong?

Thank you

**Comment by kcubeterm** [comment]
Yea, it happen sometimes with me too with golang when I compile from source, so do one thing, go to ~/go/src/GitHub/kkdai/youtube/youtubedr
and build it again by `go build ` you will find a binary

**Comment by frrobert2** [comment]
That fixed it.

Thank you

**Comment by Julian-Chu** [comment]
thank you @frrobert2 and  @kcubeterm ,
this reminds us to think about providing  binary file in release or for easy  download.

**Comment by kkc** [comment]
yes, I have the same thought. Thanks for raising this issue!
