### ISSUE TITLE
v2 is impossible to import 

### ISSUE THREAD

**Issue by fr3fou** [kkdai/youtube#99]
Trying to import v2 in a project, copying the provided `example_test.go` file, yields the following error.
![image](https://user-images.githubusercontent.com/1344906/90321627-2ccb7680-df54-11ea-85c6-4f1e3097a94b.png)

Even after updating the go.mod version like so
![image](https://user-images.githubusercontent.com/1344906/90321636-3ead1980-df54-11ea-814a-4a943f3834c0.png)
It still errors out with
```
require github.com/kkdai/youtube: version "v2.0.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

From what I understand the `module` directive in the go.mod file should be updated with `/v2` like so
```go
module github.com/kkdai/youtube/v2
```

**Comment by greentornado** [comment]
I'm getting this error too 👍

**Comment by Julian-Chu** [comment]
thank @fr3fou  and @greentornado  for this issue.

now the package should be available.
please use "go get github.com/kkdai/youtube/v2" for new version

**Comment by greentornado** [comment]
Confirmed working. thanks bro :D
